[package]
name = "rust-htslib"
version = "0.18.1-alpha.0"
authors = ["Christopher Schröder <christopher.schroeder@tu-dortmund.de>", "Johannes Köster <johannes.koester@tu-dortmund.de>"]
build = "build.rs"
description = "This library provides HTSlib bindings and a high level Rust API for reading and writing BAM files."
readme = "README.md"
keywords = ["htslib", "bam", "bioinformatics", "pileup", "sequencing"]
license = "MIT"
repository = "https://github.com/rust-bio/rust-htslib.git"
documentation = "https://docs.rs/rust-htslib"


[dependencies]
libc = "0.2"
itertools = "0.6"
quick-error = "1.2"
newtype_derive = "0.1"
custom_derive = "0.1"
url = "1.4"
ieee754 = "0.2"
lazy_static = "0.2"
bitflags = "0.9"
serde = { version = "^1", optional = true }
regex = "0.2"

[features]
default = []

[dev-dependencies]
tempdir = "0.3"
bincode = "1.0"
serde_json = "1.0"
pretty_assertions = "0.5.1"

[build-dependencies]
fs-utils = "1.0"
bindgen = "0.35.0"
